# Handling Potential Failur with Result


```rs
    .expect("Failed to read line");
```

- `read_line` puts whatever the user enters into the string we pass to it, but it also returns a `Result` value.

- An instance of `Result` has an `expect method` that you can call. If this instance of `Result` is an `Err` value, `expect` will cause the program to crash and display the message that you passed as an argument to `expect`.

If you don’t call `expect`, the program will compile, but you’ll get a warning:

```rs
$ cargo build
   Compiling guessing_game v0.1.0 (file:///projects/guessing_game)
warning: unused `Result` that must be used
  --> src/main.rs:10:5
   |
10 |     io::stdin().read_line(&mut guess);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this `Result` may be an `Err` variant, which should be handled
   = note: `#[warn(unused_must_use)]` on by default

warning: `guessing_game` (bin "guessing_game") generated 1 warning
    Finished dev [unoptimized + debuginfo] target(s) in 0.59s

```

- Rust warns that you havn't used the `Result` value  returned from `read_line` indicating that the program hasn't handled a possible error.